### ISSUE TITLE
SPE1 integration tests fail

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#177]
spe1 test case on jenkins fail with the following error. I suspect it might be some outdated webdriver issue ? https://ci.equinor.com/komodo/job/x-komodo-test-spe1_st/306/console 

```
ERROR    dash.testing.browser:browser.py:415 <<<Webdriver not initialized correctly>>>
Traceback (most recent call last):
  File "/prog/res/komodo/2021.10.b9-py38-rhel7/root/lib/python3.8/site-packages/dash/testing/browser.py", line 413, in get_webdriver
    return getattr(self, "_get_{}".format(self._browser))()
  File "/prog/res/komodo/2021.10.b9-py38-rhel7/root/lib/python3.8/site-packages/dash/testing/browser.py", line 458, in _get_chrome
    else webdriver.Chrome(options=options, desired_capabilities=capabilities)
  File "/tmp/jenkins-komodo-f_scout_ci/workspace/x-komodo-test-spe1_st/kenv/root/lib64/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/tmp/jenkins-komodo-f_scout_ci/workspace/x-komodo-test-spe1_st/kenv/root/lib64/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/tmp/jenkins-komodo-f_scout_ci/workspace/x-komodo-test-spe1_st/kenv/root/lib64/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "/tmp/jenkins-komodo-f_scout_ci/workspace/x-komodo-test-spe1_st/kenv/root/lib64/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/tmp/jenkins-komodo-f_scout_ci/workspace/x-komodo-test-spe1_st/kenv/root/lib64/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/tmp/jenkins-komodo-f_scout_ci/workspace/x-komodo-test-spe1_st/kenv/root/lib64/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 207, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: <HTML><HEAD>
```

**Comment by DanSava** [comment]
Run some tests that point to the issue with running the webviz-ert test just on st-linapp1195.st.statoil.no

Tried to ssh into `st-linapp1195.st.statoil.no` but I could not, I was able to ssh into `st-linapp1196.st.statoil.no` and I could not reproduce the issue running the same tests there.

**Comment by oysteoh** [comment]
fixing the seleniumversion seems to have fixed our problems, but we should initiate the upgrade of chromium drivers on the nodes i guess to be able to remove the pinning and move forward on the versions.
