### ISSUE TITLE
Unable to visualise ERT3 results

### ISSUE THREAD

**Issue by markusdregi** [equinor/webviz-ert#190]
**Describe the bug**
When trying to visualise ERT3 results I get a stack trace in the terminal and no data visualised.

**To Reproduce**
1. Install ert and webviz-ert, both `main`
2. Launch ert-storage via `ert3 service start storage`
3. Create example with `ert3 init --example polynomial`
4. Enter workspace with `cd polynomial`
5. Run experiment with `ert3 run evaluate`
6. Launch visualisation with `ert vis`

**Expected behavior**
Plots displaying the polynomials of the different realisations

**Stack trace**
```
Traceback (most recent call last):
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/webviz_ert/controllers/ensemble_selector_controller.py", line 79, in update_ensemble_selector_graph
    ensemble_dict = get_ensembles(project_id=parent.project_identifier)
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/webviz_ert/data_loader/__init__.py", line 264, in get_ensembles
    return get_data_loader(project_id).get_all_ensembles()
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/webviz_ert/data_loader/__init__.py", line 260, in get_data_loader
    return DataLoader(*(get_info(project_id).values()))
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/webviz_ert/data_loader/__init__.py", line 15, in get_info
    from ert_shared.storage.connection import get_info
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/ert_shared/storage/connection.py", line 4, in <module>
    from ert_shared.services import Storage
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/ert_shared/services/__init__.py", line 1, in <module>
    from .storage_service import Storage
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/ert_shared/services/storage_service.py", line 8, in <module>
    from ert_shared.services._base_service import BaseService, local_exec_args
  File "/Users/mfane/Development/demo/demo-py37/demo-env37/lib/python3.7/site-packages/ert_shared/services/_base_service.py", line 49, in <module>
    signal.signal(signal.SIGTERM, cleanup_service_files)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: firefox
 - Version: `main`

**Comment by DanSava** [comment]
Has been resolved by https://github.com/equinor/ert/pull/2413
