### ISSUE TITLE
ValueError: no types given, on startup

### ISSUE THREAD

**Issue by kwinkunks** [equinor/webviz-ert#420]
Immediately after starting the app on a template-generated poly example, both on my local machine and on an Azure RGS node, I get the following non-fatal errors:

```
ERROR:webviz_app:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/dash/dash.py", line 1274, in dispatch
    ctx.run(
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/dash/_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/webviz_ert/controllers/multi_response_controller.py", line 193, in update_graph
    response_plots = [
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/webviz_ert/controllers/multi_response_controller.py", line 194, in <listcomp>
    _generate_plot(ensemble, assets.get_color(index=index))
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/webviz_ert/controllers/multi_response_controller.py", line 180, in _generate_plot
    plot = _create_response_plot(
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/webviz_ert/controllers/multi_response_controller.py", line 122, in _create_response_plot
    realizations = _get_realizations_statistics_plots(
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib/python3.8/site-packages/webviz_ert/controllers/multi_response_controller.py", line 60, in _get_realizations_statistics_plots
    p10 = data.quantile(0.1, axis=1)
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib64/python3.8/site-packages/pandas/core/frame.py", line 11296, in quantile
    res_df = self.quantile(  # type: ignore[call-overload]
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib64/python3.8/site-packages/pandas/core/frame.py", line 11328, in quantile
    cdtype = find_common_type(list(self.dtypes))
  File "/prog/komodo/2023.02.06-py38-rhel7/root/lib64/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1608, in find_common_type
    raise ValueError("no types given")
ValueError: no types given
```

To reproduce: 

- `ssh -X s034-rgs0002.s034.oc.equinor.com`
- `source /prog/komodo/2023.02.06-py38-rhel7/enable`
- `komodoenv --no-update --root /prog/komodo kenv`
- `source kenv/enable`
- `pip install py`
- Check out `ert`, `main` branch
- `cd tests/performance_tests`
- `python performance_utils.py`  # Returns a tmp location
- `ert vis /tmp/<-tmp-location->/poly/poly.ert`

**Expected behavior**
The app should start without warnings.

**Desktop (please complete the following information):**
 - OS: Linux (local machine and on Azure)
 - Browser: Firefox

**Comment by andreas-el** [comment]
When running this locally on my mac (and on my rhel8 workstation), storage folder does not seem to be generated.
So when starting webviz-ert;

```
(dev-ert) ➜  ert git:(main) ✗ python tests/performance_tests/performance_utils.py
/var/folders/qg/h39sdwm11wl6j0c9_dwj9jyr0000gp/T/tmpep4p15ut
(dev-ert) ➜  ert git:(main) ✗ ert vis /var/folders/qg/h39sdwm11wl6j0c9_dwj9jyr0000gp/T/tmpep4p15ut/poly/poly.ert
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/ANDRLI/Project/ert/src/ert/services/_base_service.py", line 146, in run
    self._set_conn_info(conn_info)
  File "/Users/ANDRLI/Project/ert/src/ert/services/_base_service.py", line 342, in set_conn_info
    with open(path, "w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/qg/h39sdwm11wl6j0c9_dwj9jyr0000gp/T/tmpep4p15ut/poly/storage/storage_server.json'
```

**Comment by DanSava** [comment]
> When running this locally on my mac (and on my rhel8 workstation), storage folder does not seem to be generated. So when starting webviz-ert;
> 
> ```
> (dev-ert) ➜  ert git:(main) ✗ python tests/performance_tests/performance_utils.py
> /var/folders/qg/h39sdwm11wl6j0c9_dwj9jyr0000gp/T/tmpep4p15ut
> (dev-ert) ➜  ert git:(main) ✗ ert vis /var/folders/qg/h39sdwm11wl6j0c9_dwj9jyr0000gp/T/tmpep4p15ut/poly/poly.ert
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "/Users/ANDRLI/Project/ert/src/ert/services/_base_service.py", line 146, in run
>     self._set_conn_info(conn_info)
>   File "/Users/ANDRLI/Project/ert/src/ert/services/_base_service.py", line 342, in set_conn_info
>     with open(path, "w", encoding="utf-8") as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/qg/h39sdwm11wl6j0c9_dwj9jyr0000gp/T/tmpep4p15ut/poly/storage/storage_server.json'
> ```

This is designed to generate a ERT case that needs to be run before results can be visualized. That is the reason the storage folder is missing. 

So after running `python performance_utils.py` we need to run `ert gui /tmp/<-tmp-location->/poly/poly.ert` and run an experiment for the `storage` folder to be generated. 

I encountered the following issue when running the case generated by `performance_utils.py`: https://github.com/equinor/ert/issues/8433

**Comment by DanSava** [comment]
Changing `tests/performance_tests/performance_utils.py` from 
``` Python
    make_poly_example(
        folder,
        "test-data/poly_template",
        gen_data_count=3400,
        gen_data_entries=150,
        summary_data_entries=100,
        reals=200,
        summary_data_count=4000,
        sum_obs_count=450,
        gen_obs_count=34,
        sum_obs_every=10,
        gen_obs_every=1,
        parameter_entries=10,
        parameter_count=10,
        update_steps=1,
    )

```
to 
``` Python
    make_poly_example(
        folder,
        "../../test-data/poly_template",
        gen_data_count=34,
        gen_data_entries=15,
        summary_data_entries=20,
        reals=100,
        summary_data_count=40,
        sum_obs_count=10,
        gen_obs_count=4,
        sum_obs_every=2,
        gen_obs_every=1,
        parameter_entries=10,
        parameter_count=10,
        update_steps=1,
    )
```
allows the test to run and visualise the results using `ert vis /tmp/<-tmp-location->/poly/poly.ert` without any issue.
