### ISSUE TITLE
Exceptions thrown for some responses in the observation analyzer page

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#98]
For some of the responses an exception is thrown when using a database from the HM tutorial. The same responses works perfectly fine in the other views.

I have the database-file if needed for investigation. Stacktrace below 
```
Traceback (most recent call last):
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/dash/dash.py", line 1059, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/dash/dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/ertviz/controllers/observation_response_controller.py", line 121, in _update_graph
    response_plots = [
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/ertviz/controllers/observation_response_controller.py", line 122, in <listcomp>
    _generate_plot(ensemble_id, data["color"])
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/ertviz/controllers/observation_response_controller.py", line 118, in _generate_plot
    plot = _create_misfits_plot(ensemble.responses[response], None, color)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/ertviz/controllers/observation_response_controller.py", line 33, in _create_misfits_plot
    response.univariate_misfits_df(selected_realizations),
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/ertviz/models/response.py", line 66, in univariate_misfits_df
    return misfits_df.astype("float64")
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/pandas/core/generic.py", line 5546, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 595, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 406, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 2100, in astype
    return super().astype(dtype=dtype, copy=copy, errors=errors)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 595, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/Users/OOH/code/virtualenvs/ert/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 941, in astype_nansafe
    raise TypeError(f"cannot astype a datetimelike from [{arr.dtype}] to [{dtype}]")
TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float64]
```

**Comment by oysteoh** [comment]
working response looks like this in `response.py` line 66
```
                  0         1         2         3         4  ...        46        47        48        49  x_axis
ROP_5_SIM                                                    ...                                                
0          3.747192 -2.262980  5.948649  3.861511  0.911723  ...  6.283081  6.566447  5.805593  4.182485       0
1          1.597880 -1.746399  3.858907  2.685984 -0.095490  ...  4.153432  5.326528  3.527598  2.045481       1
2          4.365428  5.786051  6.596965  5.491831  3.982320  ...  6.770691  8.092295  6.303640  4.507161       2
```

not working looks like this
```
              0     1     2     3     4     5     6     7  ...    43    44    45    46    47    48    49     x_axis
WWCT:OP_3                                                  ...                                                     
0          1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  ...  1.25  1.25  1.25  1.25  1.25  1.25  1.25 2000-12-01

```
